select top 5 * from superstore;

--1. What percentage of total revenue is generated by the top 20% of customers?--
with Customer_Sales as (
    select Customer_ID, SUM(Sales) AS Total_Sales
    FROM superstore
    GROUP BY Customer_ID
),
ranked as (
    select *,
           NTILE(5) over (order by Total_Sales desc) as bucket
    from Customer_Sales
)
select 
    sum(case when bucket = 1 then Total_Sales end) * 100.0 / sum(Total_Sales) as Top_20_percent_revenue
from ranked;

--2. What is the month-over-month sales growth rate? Identify months with declining sales.--

with Monthly_Sales as (
    select 
        datetrunc(month, Order_Date) as Month,
        sum(Sales) as Total_Sales
    from superstore
   group by datetrunc(month, Order_Date)
)
select 
    Month,
    Total_Sales,
    lag(Total_Sales) over (order by Month) as prev_month,
    round(
        (Total_Sales - lag(Total_Sales) over (order by Month)) * 100.0 
        / nullif(lag(Total_Sales) over (order by Month), 0),
        2
    ) as growth_pct
from Monthly_Sales;

--3. Segment customers into High, Medium, and Low spenders based on total purchase value.--
with Customer_Total as (
    select Customer_ID, sum(Sales) as Total_Spent
    from superstore
    group by Customer_ID
)
select *,
    case 
        when Total_Spent >= 10000 then 'High'
        when Total_Spent >= 5000 then 'Medium'
        else 'Low'
    end as Segment
from Customer_Total;

--4. What proportion of customers are repeat buyers vs one-time buyers?--
with Customer_Orders AS (
    select 
        Customer_ID, 
        count(distinct Order_ID) as Order_count
    from superstore
    group by Customer_ID
)
select 
    Customer_type,
    count(*) as Num_Customers
from (
    select 
        case 
            when Order_count = 1 then 'One-Time'
            else 'Repeat'
        end as Customer_type
    from Customer_Orders
) t
group by Customer_type;

--5. What is the average delivery time, and which ship mode is the fastest and most consistent?--
select Ship_Mode,
avg(datediff(day,Order_Date,Ship_Date)) as Avg_Delivery_Time
from superstore
group by Ship_Mode
order by Avg_Delivery_Time desc;

--6. Do faster shipping methods (e.g., First Class) correlate with higher order values?--
select Ship_Mode,
avg(Sales) as Avg_Order_Value
from superstore
group by Ship_Mode
order by Avg_Order_Value desc;

--7. Which region generates the highest revenue, and which has the most consistent monthly sales?--
select Region,
sum(Sales) as Total_Rev,
stdev(Sales) as  Sales_Variability
from superstore
group by Region;

--8. Which cities have high order volume but low average order value?--
select City,
count(Order_ID) as Total_Orders,
avg(Sales) as Avg_Order_Value
from superstore
group by City
order by Total_Orders desc,Avg_Order_Value asc;

--9. Identify products that generate high revenue but are purchased infrequently.--
select Product_Name,
count(Order_ID) as order_count,
sum(Sales) as total_sales
from superstore
group by Product_Name
having count(Order_ID) < 10
order by total_sales desc;

--10. Find the top-selling product in each month.--
with Monthly_Product as (
    select
        datetrunc(month, Order_Date) as Month,
        Product_Name,
        sum(Sales) as Total_Sales
    from superstore
    group by 
        datetrunc(month, Order_Date),
        Product_Name
),
ranked as (
    select *,
           rank() over (partition by Month order by Total_Sales desc) as rnk
    from Monthly_Product
)
select *
from ranked
where rnk = 1;

--11. Find the average number of days between consecutive orders for repeat customers.--
with Customer_Orders as (
    select Customer_ID,
    Order_Date,
    lag(Order_Date) over (partition by Customer_ID order by Order_Date) as Prev_Date
    from superstore
    )
select Customer_ID,
avg(DATEDIFF(day,Prev_Date,Order_Date)) as Avg_Days_between_Orders
from Customer_Orders
where Prev_Date is not null
group by Customer_ID;

--12. Calculate a 7-day rolling average of sales to identify trends and smooth fluctuations.--
with Daily_Sales as (
    select Order_Date,
    sum(Sales) as Total_Sales
    from superstore
    group by Order_Date
    )
select Order_Date,
Total_Sales,
avg(Total_Sales) over (
order by Order_Date 
rows between 6 preceding and current row) as Rolling_Avg_7_Days
from Daily_Sales;